- name: Push the changes to github-pages-files
  uses: peaceiris/actions-gh-pages@v4
  if: github.ref == 'refs/heads/wiki-reformat'
  with:
    github_token: ${{ secrets.PAGESSECRET }}
    publish_dir: ./export
    publish_branch: github-pages-files